export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
