export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const LOGIN_ADMIN_USER = "LOGIN_ADMIN_USER";
export const LOGOUT_ADMIN_USER = "LOGOUT_ADMIN_USER";
